### ISSUE TITLE
Veřejná sféra versus veřejná správa

### ISSUE THREAD

**Issue by MikkCZ** [NUKIB/bezpecnostni-doporuceni-open-source#12]
README a název dokumentu obsahují pojem _veřejná sféra_, kterou jsem si nejdříve vysvětlil jako soukromý sektor, soukromé firmy. Dále se ale v textu vyskytuje formulace _Doporučení není pro veřejnou správu právně závazné..._ a _...připravena k připomínkám veřejné správy, dodavatelů software pro veřejnou správu ..._. Možná jsem jen neznalý pojmů, ale jaká je tedy prosím cílová skupina, pro kterou je dokument určený?

**Comment by ondj** [comment]
Omlouváme se za zmatení pojmů, primárním cílem je veřejná správa, tedy státní správa, samospráva a ostatní veřejná správa. README upravíme. Dokument ale bude veřejný, použít jej může kdokoliv, kdo bude chtít i mimo veřejnou správu.
