### ISSUE TITLE
Formát pro API aplikací

### ISSUE THREAD

**Issue by fyziktom** [NUKIB/bezpecnostni-doporuceni-open-source#18]
Měli bychom definovat, že aplikace by měli poskytovat popis API v OpenAPI formátu. Ideálně i vč. Swagger testing UI, apod.

Stejně tak by se měla definovat konektivita na MQTT či podobné IoT protokoly. Budou je potřebovat v rámci digitalizace všechny aplikace. 

Co myslíte?

**Comment by ondj** [comment]
> Měli bychom definovat, že aplikace by měli poskytovat popis API v OpenAPI formátu. Ideálně i vč. Swagger testing UI, apod.

Původně mi toto přišel spíše jako funkční požadavek, ale má souvislost i s bezpečností: špatně dokumentované API může vést k narušení integrity dat. Zapracujeme. 

> Stejně tak by se měla definovat konektivita na MQTT či podobné IoT protokoly. Budou je potřebovat v rámci digitalizace všechny aplikace.

Toto považuji už za velmi specifickou záležitost, která není vhodné řešit v rámci tohoto obecného dokumentu.
