### ISSUE TITLE
Informace o licencích

### ISSUE THREAD

**Issue by MikkCZ** [NUKIB/bezpecnostni-doporuceni-open-source#25]
Nesouvisí to přímo z bezpečnostní vývoje, ale aby projekt reálně spadal do kategorie _open source_, stálo by za to zmínit, pod jakou licencí musí být jeho kód dostupný. Případně existuje už k tomu ve státní správě nějaká jiné metodika nebo doporučení?

**Comment by ondj** [comment]
Volba vhodné licence je na samotné organizaci. V rámci tohoto dokumentu je možné doporučit požití určité licence pouze pokud by to mělo mít vliv na bezpečnost systému - dovedu si představit třeba právní spory, které by vedli k pozastavení provozování systému.
