### ISSUE TITLE
Otevřený dopis Národnímu úřadu pro kybernetickou a informační bezpečnost a Ministerstvu vnitra

### ISSUE THREAD

**Issue by MikkCZ** [NUKIB/bezpecnostni-doporuceni-open-source#33]
Dobrý den.

Náš [spolek OpenAlt z.s.](https://www.openalt.org/) aktivně propaguje otevřené technologie, softwarové i hardwarové, jejich používání, vývoj a samozřejmě osvětu v této oblasti. Neunikla nám proto vaše společná iniciativa vytvořit _Bezpečnostní doporučení pro vývoj otevřeného softwaru ve veřejné správě_.

Kromě samotného faktu, že takový dokument vůbec vzniká, velmi oceňujeme jeho zveřejnění a možnost zasílání připomínek formou komentářů (issues) i konkrétních návrhů na změny (pull requesty). Doporučení jsou formulována do poměrně jednoduché příručky, nejsou navázána na konkrétní zákonné požadavky nebo paragrafy, ale jsou použitelná obecně. Na tvorbě a doplnění dokumentu se tedy mohou podílet členové našeho spolku i další profesionálové z oboru, jak je přímo vidět z aktivity v repozitáři, takže dokument nejen open source podporuje, ale sám se jeho principy snaží řídit.

Tímto dopisem děkujeme za váš přístup a vyjadřujeme podporu při tvorbě dalších podobných dokumentů nyní i v budoucnu. Rovněž vás zveme na další ročník naší [konference OpenAlt](https://www.openalt.cz/) (dříve pod názvem LinuxAlt), kterou od roku 2006 pořádáme, a kde je i vždy silné zastoupení přednášek zaměřených na téma bezpečnosti. Uvítáme vás na ní ať už jako partnery, přednášející i návštěvníky.

S pozdravem za spolek OpenAlt z.s.
Michal Stanke, předseda

**Comment by MikkCZ** [comment]
Tento dopis v plném znění zveřejňujeme také [na našich stránkách](https://www.openalt.org/content/otev%C5%99en%C3%BD-dopis-n%C3%A1rodn%C3%ADmu-%C3%BA%C5%99adu-pro-kybernetickou-informa%C4%8Dn%C3%AD-bezpe%C4%8Dnost-ministerstvu-vnitra).

**Comment by ondj** [comment]
Děkujeme za podporu a hlavně za cenné příspěvky při tvorbě tohoto dokumentu!

Konferenci OpenAlt známe, několikrát jsme se jí účastnili jako návštěvníci. Možnost zapojení jako přednášející do příštího ročníku určitě zvážíme.

**Comment by MikkCZ** [comment]
Omlouvám se za "reklamu". Letošní ročník OpenAltu, který proběhne 18. a 19. září v Brně, přijímá přihlášeky přednášek. @ondj máte zájem nebo někdo z vašeho týmu představit smysl a vznik tohoto dokumentu? Případně budou vítané i jakékoliv další přednášky z NÚKIB. Neváhejte rovnou přednášku přihlásit, nebo napište na kontaktní e-mail https://www.openalt.cz/2022/kontakt.php, kde rádi pomůžeme nebo odpovíme na dotazy.

Za OpenAlt
Michal Stanke
